### ISSUE TITLE
🔨[refactor] [v1.0.0] 프로덕션용 배포 준비 

### ISSUE THREAD

**Issue by ImNM** [Gosrock/Ticket-Backend-22th#89]
# 🔨 리팩토링이 필요한 부분 

화요일 밤에 (8월 2일 ) 백엔드 회의 진행할 예정입니다.

# 리팩토링 작업 브런치

각 개선점 refactor 항목으로

### ✅ refactoring TODO

- [ ]

**Comment by ImNM** [comment]
테스트 통과하게끔 유저 서비스 수정

**Comment by ImNM** [comment]
어세스토큰 담는정보 (관리자로그인 ) 길이 수정

**Comment by ImNM** [comment]
응원댓글 렌덤하게 뽑아오는  api 추가

**Comment by ImNM** [comment]
유저 조회시 createdAt
댓글 조회 성공시 유저정보 빼기 ,
유저 조회시 검색 전화번호, 이름

**Comment by ImNM** [comment]
https://api.gosrock.band/api-docs/#/tickets/TicketsController_getAllTicketsById
요청 성공응답시 
유저 정보 빼기
어드민 정보도 필요없겟징

**Comment by ImNM** [comment]
https://api.gosrock.band/api-docs/#/tickets/TicketsController_postTicketEntryValidation
확인대기 인 티켓인데 에러메시지가
{
  "statusCode": 400,
  "timestamp": "2022-08-02T12:56:56.031Z",
  "path": "/v1/tickets/uzByTqadZLoGPo/enter",
  "method": "POST",
  "error": {
    "message": "이미 입장 완료된 티켓입니다",
    "error": "BadRequestException",
    "statusCode": 400
  }
}
이거임
@gengminy

**Comment by ImNM** [comment]
https://api.gosrock.band/api-docs/#/tickets/TicketsController_updateTicketStatus

티켓 상태 변경을 했는데
티켓 입장 알람이 와버림
@sanbonai06

**Comment by ImNM** [comment]
https://api.gosrock.band/api-docs/#/tickets/TicketsController_getTicketsWith

    .orderBy('ticket.createdAt', pageOptionsDto.order)
createdAt이 아닌 id 기준으로!
@gengminy

**Comment by kim-wonjin** [comment]
관리자 현황조회 공짜티켓 갯수 추가

**Comment by kim-wonjin** [comment]
관리자 주문조회 페이지네이션 isFree 다시 넣기
